{% set name = "hyperopt" %}
{% set version = "0.1.1a" %}
# 0.1.1a is not a real version; but 0.1.0 was released a year ago, so this will do for now.

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/hyperopt/hyperopt.git
  git_rev: 7e247f5963d05f6e7e9299ff59bc90b126ef7987

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - pymongo
    - six
    - networkx
    - future

test:
  requires:
    - nose
    - pytest
    - ipython
    - matplotlib
  imports:
    - hyperopt
    - hyperopt.tpe
  commands:
    # Upstream failures (see, e.g., https://github.com/hyperopt/hyperopt/issues/315):
    - py.test --pyargs hyperopt --tb=short -k "not test_basic and not test_mu_is_used and not test_cdf and not test_pdf_logpdf and not test_random and not TestExperimentWithThreads and not test_plot and not test_q1lognormal"

about:
  home: http://hyperopt.github.io/hyperopt/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Distributed Asynchronous Hyperparameter Optimization in Python'
  description: |
    Hyperopt is a Python library for serial and parallel optimization over awkward
    search spaces, which may include real-valued, discrete, and conditional
    dimensions.
  doc_url: http://hyperopt.github.io/hyperopt/
  dev_url: https://github.com/hyperopt/hyperopt

extra:
  recipe-maintainers:
    - aldanor
